### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by Dremor** [oskardotglobal/gottagofast-fabric#2]
Hi.

Would it be possible to make this mod available to the latest 1.19.x version (currently 1.19.4) ?

Thank you in advance.

**Comment by oskardotglobal** [comment]
> Did you try the mod in 1.19.4? If it doesn't work, I can still update it, but I think it should.
Ignore that. I'm mostly a plugin developer, where that kinda stuff isn't a problem. I'll port to 1.19.4 soon

**Comment by Dremor** [comment]
The problem is mainly because of the hard dependency to Minecraft 1.19.3. If it is possible to allow any compatible version like Phosphor would do, it would be ideal.

**Comment by Dremor** [comment]
See following examples:
- [TimeOutOut](https://github.com/PotatoPresident/TimeOutOut/blob/master/src/main/resources/fabric.mod.json)
- [Phosphor](https://github.com/CaffeineMC/phosphor-fabric/blob/1.19.x/dev/src/main/resources/fabric.mod.json)

**Comment by oskardotglobal** [comment]
[Here's a version which should be compatible with 1.19.4 & 1.19.3](https://github.com/oskardotglobal/gottagofast-fabric/releases/download/1.0.3/gottagofast-1.0.2.jar)

If it works, I can release that, so please tell me any issues when they arise

**Comment by Dremor** [comment]
Sorry for the delay. Yes, it works.
