### ISSUE TITLE
1.20.x

### ISSUE THREAD

**Issue by Charadon** [oskardotglobal/gottagofast-fabric#4]
Just curious if there's going to be a update to support 1.20

**Comment by oskardotglobal** [comment]
Of course, expect an update in the next few days.

**Comment by oskardotglobal** [comment]
https://modrinth.com/mod/gotta-go-fast-fabric/version/HFcUMnsT
Try this and report back if it works.

**Comment by APerfectPenguin** [comment]
Tried the above version, mod claims it was loaded in console during startup, however when going up slabs on a horse it still has intense rubberbanding with console spam of "Horse (vehicle of user) moved too quickly!" - increasing mod's move speed for vehicles in config seemingly has no effect.

This might be an entirely seperate thing, just hoped it would fix the horses lol

**Comment by oskardotglobal** [comment]
It should fix the horses

**Comment by oskardotglobal** [comment]
I'll look into it

**Comment by oskardotglobal** [comment]
@APerfectPenguin 

I've finished the rewrite. Didn't have time to test it, so please report back with what you found.
The mod will now log the "moved too quickly" messages by default and the default limits will be set to the vanilla limits. However, the log messages contain a new threshold which would exclude the particular "too fast" movement, so it's probably easiest to get new values via that.

https://modrinth.com/mod/gotta-go-fast-fabric/version/1.1.0
(also requires owo-lib)

@xAffan this should also work with 1.20.1

**Comment by Magicrafter13** [comment]
I just got `[Server thread]: [ServerGamePacketListenerImpl] Magicrafter13 moved too quickly! 0.6378242257701459,0.0,10.4052376973425` with the new jar.

**Comment by oskardotglobal** [comment]
Closing this as it has shifted to another problem unrelated to the update.
@Magicrafter13 @APerfectPenguin Continuing to address this in #6 as it's kind of related to the mod and is something I wanted the mod to fix anyways.

Thanks to everyone for their contributions!
