### ISSUE TITLE
1.20.1 version doesnt work on quilt server

### ISSUE THREAD

**Issue by Rozbiynk** [oskardotglobal/gottagofast-fabric#7]
![изображение](https://github.com/oskardotglobal/gottagofast-fabric/assets/95433246/0318685c-b0a3-4125-a593-d9bb133f85cc)
![изображение](https://github.com/oskardotglobal/gottagofast-fabric/assets/95433246/83aba19b-bfa3-433e-a637-89352a4cf516)
https://mclo.gs/E1S5J9t latest log

**Comment by Rozbiynk** [comment]
im try million value and its doesnt work too

**Comment by Rozbiynk** [comment]
look like carpet fix that

**Comment by oskardotglobal** [comment]
Quilt isn't actively being worked on or tested. I'll look into it

**Comment by oskardotglobal** [comment]
Also, what do you mean by "carpet fixes this"

**Comment by Rozbiynk** [comment]
i mean i disabled antichear on carpet and it was fixed

**Comment by oskardotglobal** [comment]
That works, but isn't a good idea.

> ... or being kicked out for 'flying'
> Increases player allowed mining distance to 32 blocks

See [the carpet wiki](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings#anticheatdisabled)

**Comment by oskardotglobal** [comment]
Quilt will be officially supported *soon™*

**Comment by Mitferitch** [comment]
On the Fabric server, it also does not work on the 1.1.0 version of the mod, but if you put the 1.0.2 version of the mod on the server, then everything works. I checked everything in Minecraft 1.20.1. For 1.0.2 I changed the version to 1.20.1.

**Comment by oskardotglobal** [comment]
Also, how does your config look
@Mitferitch

**Comment by Mitferitch** [comment]
I used the mod for a month on version 1.0.2 and everything was fine. Today I decided to switch to 1.1.0 and after that the messages "Player moved too quickly!" appeared and the players began to be thrown back.
[14:07:35] and [14:18:50]
Now I'm using version 1.0.2 again and everything is fine again
[2023-07-10-6 (1).log.gz](https://github.com/oskardotglobal/gottagofast-fabric/files/12002589/2023-07-10-6.1.log.gz)

**Comment by Mitferitch** [comment]
I have not changed the configs in any way
![image](https://github.com/oskardotglobal/gottagofast-fabric/assets/139130362/52ad80ae-21fd-4b46-8ee6-a6a76dcf34ea)
![image](https://github.com/oskardotglobal/gottagofast-fabric/assets/139130362/b8a8af28-874d-4103-8449-0e2711aabd96)

**Comment by oskardotglobal** [comment]
@Mitferitch 
The default values are the vanilla values. Increase them slowly until the issues disappear. The mod does nothing by default, this is intended behaviour. Should probably point this out on the readme better
